# Site settings
title: Yukyung Kim's CV
description: YuKyung Kim's CV
favicon: /assets/img/avatar.jpg
baseurl:
url: https://yukyungkim.github.io/
rss_url: /pages/atom.xml
# google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: 김유경 (Yu Kyung Kim)
  title: Software Developer
  address: Seoul, Republic of Korea
  email: whee6409@gmail.com
  # link: http://ddbullfrog.com
  weibo:
  github: yukyungkim
  linkedin:
  twitter:
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  educationHistory:
    - education1:
      organization: Software Maestro 6th
      location: 미래창조과학부 정보통신기술진흥센터
      degree: 연수생
      major: Embedded Software, Android Application Develope
      started: 2016
      duration: (2015.07 - 2016.06)
      description: 미래창조과학부에서 매년 100명의 연수생을 선발하여 다양한 분야의 현업 멘토들과 함께 도제식 교육을 통해 단계별 프로젝트를 수행하여 Software 개발 인재를 양성하는 교육 과정이다. <br/>1단계 1차 프로젝트(2015.08 ~ 09)에서는 SKT의 스마트 로봇 알버트를 이용한 안드로이드 알람 어플리케이션을 개발하였다. <br/>1단계 2차 프로젝트(2015.09 ~ 11)에서는 TCP/IP와 UDP/IP 통신으로 드론을 조종하는 안드로이드 어플리케이션을 개발하였다. <br/>2단계 프로젝트(2015.12 ~ 2016.06)에서는 IoT 공유 공간 출입 통제 장치를 개발하고, 장치의 기본 정보 설정용 안드로이드 어플리케이션과 공유 공간을 예약하기 위한 안드로이드 어플리케이션을 개발하였다.  <br/>각 프로젝트 상세 정보는 아래 Project History에서 확인할 수 있다.
    - education2:
      organization: 국민대학교(Kookmin University)
      location: 서울시 성북구
      degree: 학사 졸업
      major: 전자공학부 (부전공 컴퓨터공학부)
      started: 2015
      duration: (2010.03 - 2015.08)
      description: 과내 소프트웨어 학술 동아리에서 활동하며 소프트웨어 개발 관련 세미나, 스터디 등을 진행하였다. 학부 내의 소프트웨어 개발 관련 수업과 함께 컴퓨터공학부에 개설된 여러 수업을 함께 수강하였다.
    - education3:
      organization: NHN Software Membership 예비과정
      location: NHN
      degree: 연수생
      major:
      started: 2013
      duration: (2012.12 - 2013.06)
      description: NHN에서 운영한 비전공자 대상 소프트웨어 개발 인재 양성 교육 프로그램이다. C, Java와 같은 기초 개발 언어와 개발에 필요한 기초 지식에 대한 교육을 받고, JSP 웹 어플리케이션을 개발하였다. 프로젝트 상세 정보는 아래 Project History에서 확인할 수 있다.
  projectHistory:
    - project1:
      title: All Door
      company: Software Maestro 6기 2단계 프로젝트
      location: 팀장. 안드로이드 어플리케이션 개발. 기획 및 설계.
      started: 2016
      duration: (2015.12 - 2016.06)
      description: 공유 공간 출입 통제 IoT 장치와 공유 공간 예약 시스템을 개발한 프로젝트이다. <br/>IoT 잠금장치의 블루투스 부분과 MCU 내부 EEPROM에 WiFi 및 관리자 비밀번호 등의 셋팅 정보 저장 부분과, 사용자가 공유 공간을 예약 하고, 예약 내역을 확인하거나 공간의 정보를 확인하는 등의 기능을 갖춘 안드로이드 어플리케이션을 구현하였다. <br/><img src="http://i.imgur.com/3bp9bg4.jpg" width="300px"><img src="http://i.imgur.com/LhSDQpT.jpg" width="300px"> <br/><img src="http://i.imgur.com/nypesZh.jpg" width="500px"><br/><img src="http://i.imgur.com/ue0fTDi.jpg" width="500px"><br/><img src="http://i.imgur.com/u29ViDr.jpg" width="500px"><br/><img src="http://i.imgur.com/lyHm3L2.jpg" width="500px"><br/>
    - work2:
      title: PI-Drone
      company: Software Maestro 6기 1단계 2차 프로젝트
      location: 안드로이드 어플리케이션 개발. 기획 및 설계.
      started: 2015
      duration: (2015.09 - 2015.11)
      description: Rapsberry PI를 이용해 Open Source 드론 OS를 개발한 프로젝트이다. <br/>TCP/IP와 UDP/IP를 통해 드론의 동작을 조종하고, 드론의 평형유지(Hovering) 제어에 필요한 PID제어 변수값을 조정할 수 있으며, 수평계 기능을 구현한 안드로이드 어플리케이션을 구현하였다.<br/><img src="http://i.imgur.com/N8kDBKA.jpg" width="500px"><br/><img src="http://i.imgur.com/IsWI2MM.png" width="500px"><br/><img src="http://i.imgur.com/HTAkLLQ.png" width="300px"><br/>
    - work3:
      title: 자취봇
      company: Software Maestro 6기 1단계 1차 프로젝트
      location: 팀장. 안드로이드 어플리케이션 개발. 기획 및 설계.
      started: 2015
      duration: (2015.07 - 2015.08)
      description: SKT의 스마트 로봇인 알버트를 이용해 알버트의 움직임과 알람으로 자취생들에게 도움을 주는 안드로이드 어플리케이션을 개발한 프로젝트이다. <br/>알버트 Smart Robot API를 통해 알버트의 동작을 제어하고, 안드로이드 어플리케이션에서는 SK Planet의 Weather Planet API, Google Calendar API 등을 이용해 현재 날씨나 강수 확률, 그 날의 일정 정보를 받아와 알버트에 알람 정보를 보낸다. 또한 쓰레기 처리나 빨래, 청소 등의 집안일 정보를 기록하여 관리할 수 있고 모닝콜 등의 알람을 설정할 수 있다. <br/>블루투스를 이용해 알버트와 스마트폰을 연결하고 배터리 정보를 읽어오는 부분, 날씨 및 일정 알림을 켜고 끄는 부분, SK Planet의 날씨 API를 사용해 날씨 정보를 읽어 화면에 구성하는 부분, 집안일 정보와 알람을 추가하는 부분 등을 담당하였다.<br/><img src="http://i.imgur.com/gAQT4mm.png" width="300px">
    - work4:
      title: Preflayer
      company: 경량 고속 블록 암호 LEA 구현 경진대회 장려상 수상작.
      location: 웹 어플케이션 개발. 기획 및 설계.
      started: 2014
      duration: (2014.03 - 2014.06)
      description: 사용자의 안드로이드 음악 재생 어플리케이션을 조작하는 행동 패턴에 따라 선호하는 음악과 그렇지 않은 음악을 분석하고, 선호도가 낮은 음악은 재생 목록에서 정리하거나 자신의 선호 음악 목록을 공유할 수 있도록 한 프로젝트이다. <br/>사용자 전체의 음악 차트와 선호 음악 목록을 조회하는 기능을 가진 웹 어플리케이션 구현을 담당하였다.
    - work5:
      title: PAPYRUS
      company: NHN Software Membership 예비과정 프로젝트
      location: 팀장. 웹 어플케이션 개발. 기획 및 설계.
      started: 2013
      duration: (2013.02 - 2013.06)
      description: SNS의 멀티미디어 연대표를 만들 수 있는 Timeline.js를 사용하여 인물의 일대기나 사건의 진행 순서 등을 미디어 연대표로 만들고, 그 연대표를 응용하여 텍스트 형식의 컨텐츠를 창작할 수 있도록 하는 서비스를 제공하는 웹 어플리케이션을 개발한 프로젝트이다. <br/>사용자가 입력한 정보를 받아 미디어 연대표를 구성하는 부분의 DB, Server, Front-end 등 동작에 필요한 사항을 모두 구현하였고, 전체 어플리케이션의 UI와 팀원들이 구현한 소스코드를 병합하는 역할을 담당하였다.
    - work6:
      title: Charming Charm
      company: 국민대학교 캡스톤 디자인 작품 전시회 은상 수상작.
      location: 통신, 영상처리.
      started: 2013
      duration: (2013.03 - 2013.06)
      description: 키넥트와 ATmega128을 이용하여 참참참 게임을 구현한 프로젝트이다. <br/>ATmega128과 키넥트 간의 Serial 통신을 구현하고 키넥트를 이용해 얼굴의 방향을 파악하는 부분을 담당하였다.
  #languages:
  #  - language1:
  #    name: 한국어
  #    proficiency: 모국어
  #  - language2:
  #    name: 영어
  #    proficiency:
  programmingSkills:
    - skill1:
      name: Java
      percentage: 80%
    - skill2:
      name: Android
      percentage: 60%
    - skill3:
      name: C
      percentage: 70%
    - skill4:
      name: HTML
      percentage: 30%
    - skill5:
      name: JSP
      percentage: 50%
